/* Direct Action · briefs. Fifty projects that worked somewhere, each a brief for here.
   g kinds of life · roles businesses that can carry it · m months to start (0 = Jan) · i s h lines, 48 characters at most.
   {biz} a business tied by string, else its role · {place} the suburb. */
window.DA_BRIEFS = [
  { id: "B01", th: "heat", t: "A cool room on every block", after: "Climate Shelters Network", city: "Barcelona", yr: 2020, fact: "500 shelters by summer 2026", url: "https://beteve.cat/medi-ambient/500-refugis-climatics-barcelona-estiu-2026/",
    g: ["human"], roles: ["space","owner","reuse","coop","studio","fashion","label"], m: [10,11,0,1,2], dz: ["heat","nights"], adds: [],
    i: "A cool room within 10 min of every door", s: "An open door is infrastructure.", h: "{biz}: cool room 1–5 pm, days over 35°C" },
  { id: "B02", th: "heat", t: "Turn a schoolyard into an oasis", after: "OASIS schoolyards", city: "Paris", yr: 2018, fact: "about 130 schoolyards by 2023", url: "https://www.paris.fr/pages/les-cours-oasis-7389",
    g: ["human","bee","bird"], roles: ["studio","grower"], m: [2,3,4,5], dz: ["heat","drought"], adds: ["canopy","diversity"],
    i: "The schoolyard is the street’s coolest room", s: "Unseal the ground.", h: "Map the hottest yard in {place} on A3" },
  { id: "B03", th: "heat", t: "Join the shade, block to block", after: "Green Corridors", city: "Medellín", yr: 2016, fact: "about 2°C cooler; Ashden Award 2019", url: "https://www.unep.org/news-and-stories/story/medellin-shows-how-nature-based-solutions-can-keep-people-and-planet-cool",
    g: ["bird","parrot","possum","flyingfox","bee","mammal"], roles: ["grower","studio","owner"], m: [3,4,5,6], dz: ["heat","drought"], adds: ["canopy","pollination","diversity"],
    i: "Shade joins up from the creek to the park", s: "Connect canopy; don’t just plant trees.", h: "Plant the 3 widest shade gaps this autumn" },
  { id: "B04", th: "heat", t: "Give every old tree an address", after: "Trees with email addresses", city: "Melbourne", yr: 2013, fact: "about 3,000 emails to trees by 2015", url: "https://proarbmagazine.com/the-melbourne-treemail-phenomenon/",
    g: ["plant"], roles: ["studio","space","owner"], m: [9,10,11,0,1,2], dz: ["drought"], adds: ["canopy"],
    i: "Every old tree has someone who notices", s: "Give the tree an address.", h: "QR-tag 10 old trees; water each fortnight" },
  { id: "B05", th: "heat", t: "White roofs on the strip", after: "NYC CoolRoofs", city: "New York", yr: 2009, fact: "over 12 million sq ft coated by 2025", url: "https://www.healthbeat.org/newyork/2025/06/25/cool-roofs-nyc-extreme-heat-climate/",
    g: ["human","possum","bat"], roles: ["studio","owner","space"], m: [9,10,11], dz: ["heat","nights"], adds: [],
    i: "Flat roofs throw the heat back by December", s: "Cool the roof before the room.", h: "Coat {biz}’s flat roof white; log the heat" },
  { id: "B06", th: "heat", t: "Pin the heat, not the bat", after: "Victorian Response Plan for Heat Stress in Flying-foxes", city: "Victoria", yr: 2024, fact: "triggers above 38°C with humidity under 30%; 4,790 died at Yarra Bend in 2009", url: "https://www.wildlife.vic.gov.au/__data/assets/pdf_file/0027/695601/Victorian-Response-Plan-for-Heat-Stress-in-Flying-Foxes-2024.pdf",
    g: ["flyingfox"], roles: ["studio","space","owner"], m: [9,10,11,0,1,2], dz: ["heat"], adds: [],
    i: "Every fallen flying-fox is pinned, not held", s: "Report, don’t rescue.", h: "Pocket cards: pin it in the app, call 136 186" },
  { id: "B07", th: "heat", t: "Plant a tiny forest", after: "Tiny Forest", city: "UK and Glen Waverley", yr: 2020, fact: "over 250 in the UK; Monash planted one in 2024", url: "https://earthwatch.org.uk/program/tiny-forest/",
    g: ["bird","bee","beetle","plant","lizard","spider","fungi"], roles: ["grower","studio","space"], m: [4,5,6,7], dz: ["heat","drought"], adds: ["canopy","diversity"],
    i: "A tennis-court forest where the car park was", s: "Dense, native, now.", h: "600 seedlings, 200 m², 30 people, one winter" },
  { id: "B08", th: "heat", t: "Lift the asphalt, one car space at a time", after: "Depave", city: "Portland", yr: 2008, fact: "over 360,000 sq ft removed by 2024", url: "https://www.portland.gov/bps/cleanenergy/news/2024/6/7/returning-concrete-jungles-nature",
    g: ["frog","plant","beetle","segmented"], roles: ["owner","space","grower"], m: [3,4,5,6], dz: ["drought","heat"], adds: ["canopy","diversity"],
    i: "One car space per block drinks the rain", s: "Break the seal.", h: "Lift one car space at {biz}; plant grasses" },
  { id: "B09", th: "heat", t: "Give one street back for a summer", after: "Superblocks", city: "Barcelona", yr: 2016, fact: "NO₂ down 25% at the Sant Antoni superblock", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11831821/",
    g: ["human","bird"], roles: ["owner","space","market"], m: [9,10,11,0,1,2], dz: ["heat"], adds: ["canopy"],
    i: "One street in {place} is shade, not parking", s: "Streets are rooms.", h: "Close one block on a Sunday; log the heat" },
  { id: "B10", th: "heat", t: "A phone tree for the heat", after: "Telecross REDi", city: "Australian Red Cross", yr: null, fact: "calls people at risk during heatwaves", url: "https://preparecenter.org/story/telecross-redi-heatwave-service/",
    g: ["human"], roles: ["owner","space","coop"], m: [10,11,0,1,2], dz: ["heat","nights"], adds: [],
    i: "No one spends a 40° day without a voice", s: "Check-ins go by stairwell, not app.", h: "A lobby roster: one call before 11 am" },
  { id: "B11", th: "water", t: "Turn a concrete channel into ponds", after: "Chain of Ponds", city: "Moonee Ponds Creek", yr: 2018, fact: "15 organisations signed on in 2018", url: "https://www.melbournewater.com.au/services/projects/chain-ponds-collaboration",
    g: ["frog","waterbird","turtle","dragonfly"], roles: ["studio","grower","space"], m: [2,3,4,5,6,7,8], dz: ["drought"], adds: ["diversity"],
    i: "The channel holds ponds through the dry", s: "Slow the water down.", h: "Walk the channel; draw where pond one goes" },
  { id: "B12", th: "water", t: "A raingarden at every downpipe", after: "10,000 Raingardens", city: "Melbourne Water", yr: 2008, fact: "10,000 built by 2013", url: "https://stormwater.wef.org/2013/09/australian-stormwater-controls-must-combat-droughts-floods/",
    g: ["frog","dragonfly","bee"], roles: ["owner","grower","studio"], m: [3,4,5,6,7], dz: ["drought","litter"], adds: ["diversity","pollination"],
    i: "Every downpipe feeds a garden, not a drain", s: "Rain is a resource.", h: "A raingarden at {biz}’s downpipe by May" },
  { id: "B13", th: "water", t: "Keep the wetland wet", after: "Trin Warren Tam-boore wetland", city: "Royal Park", yr: 2006, fact: "up to 160 ML of stormwater a year", url: "https://urbanwater.melbourne.vic.gov.au/projects/wetlands/wetlands-sample-project/",
    g: ["frog","waterbird","turtle","dragonfly"], roles: ["studio","space"], m: [9,10,11,0,1,2], dz: ["drought"], adds: ["diversity"],
    i: "The wetland stays wet through the dry", s: "Clean water is habitat.", h: "A frog-call night; post the calls at {biz}" },
  { id: "B14", th: "water", t: "Count the frogs before the ponds dry", after: "Frog Census", city: "Melbourne Water", yr: 2001, fact: "an app since 2016", url: "https://www.ces.vic.gov.au/soe2023/stories/citizen-scientists-growing-our-knowledge-growlers",
    g: ["frog"], roles: ["space","owner","studio"], m: [8,9,10,11], dz: ["drought","births"], adds: ["diversity"],
    i: "Every pond is heard before it dries", s: "Listen before it goes quiet.", h: "One minute of calls on Frog Census, weekly" },
  { id: "B15", th: "water", t: "Mark the turtle crossings", after: "TurtleSAT", city: "Australia", yr: 2014, fact: "35,451 turtle records by October 2026", url: "https://www.turtlesat.org.au/",
    g: ["turtle"], roles: ["studio","space","owner"], m: [9,10,11,0], dz: ["drought"], adds: ["diversity"],
    i: "No turtle dies on a creek road this summer", s: "Map the crossing, then make it.", h: "Log turtles on TurtleSAT; sign 2 crossings" },
  { id: "B16", th: "water", t: "Catch the litter at the drain", after: "LittaTrap drain baskets", city: "Enviropod", yr: null, fact: "catches plastic over 5 mm; emptied by hand", url: "https://www.enviropod.com/en-au/products/littatrap",
    g: ["turtle","waterbird","rodent"], roles: ["litter","coop","owner"], m: [9,10,11,0,1,2,3], dz: ["litter"], adds: [],
    i: "Nothing sold at {biz} reaches the creek", s: "Catch it at the drain, not the bay.", h: "A drain basket at {biz}; empty it Fridays" },
  { id: "B17", th: "water", t: "Adopt the drain outside", after: "Adopt-a-Drain", city: "Minnesota", yr: 2014, fact: "nearly 20,000 drains adopted by 2023", url: "https://www.hamline.edu/news/2023/04/hamlines-adopt-drain-program-expands-five-states",
    g: ["frog","turtle","aquatic"], roles: ["litter","runoff","owner","studio"], m: [9,10,11,0,1,2,3,4], dz: ["litter"], adds: [],
    i: "Every drain has a name and a keeper", s: "The gutter is the creek’s first metre.", h: "Name the drain outside {biz}; clear it" },
  { id: "B18", th: "water", t: "Bring a crew to the creek", after: "Merri Creek Management Committee", city: "Merri Creek", yr: 1989, fact: "six councils and the community since 1989", url: "https://mcmc.org.au/origins-of-mcmc",
    g: ["frog","waterbird","turtle","plant"], roles: ["space","owner","grower","litter"], m: [3,4,5,6,7], dz: ["drought","litter"], adds: ["diversity","canopy"],
    i: "Each shop keeps its stretch of creek", s: "Your radius is your responsibility.", h: "Three from {biz} at a creek planting day" },
  { id: "B19", th: "pollinate", t: "Plant a line, not a garden", after: "The Pollinator Pathway", city: "Seattle", yr: 2008, fact: "a mile of planting strips", url: "https://en.wikipedia.org/wiki/The_Pollinator_Pathway",
    g: ["bee","butterfly","fly","wasp","bird"], roles: ["grower","owner","studio"], m: [2,3,4,5], dz: ["flower"], adds: ["pollination","diversity"],
    i: "Nature strips flower in turn all year", s: "Plant a line, not a garden.", h: "Ten strips in a row, indigenous flowers" },
  { id: "B20", th: "pollinate", t: "Flowering roofs on tram stops", after: "Green-roofed bus shelters", city: "Utrecht", yr: 2019, fact: "316 shelters, 2,000 m² of roof", url: "https://www.utrecht.nl/city-of-utrecht/green-roofed-bus-shelters-in-utrecht",
    g: ["bee","butterfly","human"], roles: ["studio","owner"], m: [2,3,4,5,6], dz: ["heat","flower"], adds: ["pollination"],
    i: "Every tram stop wears a flowering roof", s: "Shade that flowers.", h: "Mock up a sedum roof for one tram stop" },
  { id: "B21", th: "pollinate", t: "Map a bee line across the suburb", after: "B-Lines", city: "UK", yr: 2021, fact: "the first 1,500 hectares delivered", url: "https://www.buglife.org.uk/news/new-plan-for-uk-wide-insect-superhighways-launched/",
    g: ["bee","butterfly","beetle","fly","wasp","bug","grasshopper"], roles: ["grower","studio"], m: [2,3,4,5], dz: ["flower"], adds: ["pollination","diversity"],
    i: "A flowering line crosses {place}", s: "Join the dots.", h: "Map flowers in 500 m; plant the worst gap" },
  { id: "B22", th: "pollinate", t: "A brick for native bees", after: "Bee bricks in new buildings", city: "Brighton & Hove", yr: 2020, fact: "required in new buildings over 5 m", url: "https://www.dezeen.com/2022/01/24/bee-bricks-planning-requirement-brighton/",
    g: ["bee"], roles: ["studio"], m: [9,10,11,0,1,2,3,4,5,6,7,8], dz: ["flower"], adds: ["pollination"],
    i: "Every new wall holds a native bee nest", s: "Build habitat in, not on.", h: "Design a bee brick; ten in the next wall" },
  { id: "B23", th: "pollinate", t: "Register the food plants", after: "Monarch Waystations", city: "Monarch Watch", yr: 2004, fact: "58,776 registered by September 2026", url: "https://www.monarchwatch.org/waystations/",
    g: ["butterfly","bee"], roles: ["grower","owner","studio"], m: [2,3,4,9,10], dz: ["flower"], adds: ["pollination"],
    i: "50 gardens each host a caterpillar plant", s: "Register the habitat.", h: "Plant native nettle or grass; map each one" },
  { id: "B24", th: "diversity", t: "Every backyard a stepping stone", after: "Gardens for Wildlife Victoria", city: "Victoria", yr: 2016, fact: "22 council programs", url: "https://gardensforwildlifevictoria.com/affiliates/",
    g: ["bird","lizard","bee","frog","orb","spider","mantis","snail"], roles: ["grower","owner"], m: [2,3,4,5,8,9], dz: ["flower","drought"], adds: ["diversity","pollination"],
    i: "Every backyard is a stepping stone", s: "Messy is shelter.", h: "Book a Gardens for Wildlife visit; plant 3" },
  { id: "B25", th: "diversity", t: "Count the hollows before the heat", after: "Hollows as Homes", city: "Sydney", yr: 2016, fact: "30 councils at launch", url: "https://australian.museum/blog-archive/science/hollows-as-homes-citizen-science-project/",
    g: ["possum","parrot","owl","bat"], roles: ["studio","grower"], m: [8,9,10,11], dz: ["births","heat"], adds: ["diversity"],
    i: "Every hollow tree in {place} is kept", s: "Count the hollows before the heat.", h: "Survey the 5 oldest trees; photo each hollow" },
  { id: "B26", th: "night", t: "Lights out for the migration", after: "Lights Out Chicago", city: "Chicago", yr: 1995, fact: "11 times fewer bird collisions in spring", url: "https://www.chicago.gov/city/en/progs/env/lights_out_chicago.html",
    g: ["moth","bird","bat"], roles: ["light","owner","space"], m: [8,9,10,11], dz: ["light"], adds: ["diversity"],
    i: "Dark enough for a Bogong to find the Alps", s: "Dark is a habitat.", h: "{biz}: window lights off at close to Dec" },
  { id: "B27", th: "night", t: "Relight the creek path for feet, not sky", after: "National Light Pollution Guidelines for Wildlife", city: "Australia", yr: 2020, fact: "bats added in 2023", url: "https://tethys.pnnl.gov/publications/national-light-pollution-guidelines-wildlife",
    g: ["bat","moth","owl"], roles: ["light","studio","space"], m: [9,10,11,0,1,2], dz: ["light"], adds: ["diversity"],
    i: "Light the creek path for feet, not sky", s: "Light only what is needed, when.", h: "Redesign 5 creek lights warm, low, timed" },
  { id: "B28", th: "diversity", t: "Four days to count everything", after: "City Nature Challenge", city: "worldwide", yr: 2016, fact: "3,001,825 observations in 2026", url: "https://www.citynaturechallenge.org/",
    g: ["any"], roles: ["space","studio","owner"], m: [3], dz: [], adds: ["diversity"],
    i: "{place} records more life in 4 days than ever", s: "What is counted can be cared for.", h: "A bioblitz from {biz} in late April" },
  { id: "B29", th: "night", t: "Track the Bogongs", after: "Moth Tracker", city: "Zoos Victoria", yr: 2019, fact: "500 verified Bogong records by 2024", url: "https://www.abc.net.au/news/2019-09-18/bogong-moth-tracker-rolled-out-endangered-pygmy-possums-at-risk/11520512",
    g: ["moth"], roles: ["light","space","owner"], m: [8,9,10,11], dz: ["light"], adds: ["diversity"],
    i: "Every Bogong here is logged and let go", s: "Count the travellers.", h: "Log Bogongs on Moth Tracker; free at dark" },
  { id: "B30", th: "diversity", t: "Take back the old rat baits", after: "BirdLife Australia rat poison campaign", city: "Australia", yr: 2021, fact: "over 90 native species exposed", url: "https://birdlife.org.au/protect-aussie-birds-from-lethal-sgar-rat-poisons",
    g: ["owl","raptor"], roles: ["poison","owner","grower"], m: [9,10,11,0,1,2,3,4,5,6,7,8], dz: ["poison"], adds: ["diversity"],
    i: "No owl in {place} dies of a poisoned rat", s: "Trap, don’t poison.", h: "{biz} takes back baits, gives snap traps" },
  { id: "B31", th: "food", t: "Grow food where people walk", after: "Incredible Edible", city: "Todmorden", yr: 2008, fact: "food growing in public places", url: "https://www.incredible-edible-todmorden.co.uk/",
    g: ["bee","bird","human"], roles: ["owner","grower","market"], m: [2,3,4,8,9], dz: ["flower"], adds: ["food","pollination"],
    i: "Herbs grow free for anyone outside {biz}", s: "Food is a commons.", h: "A help-yourself herb bed at {biz}" },
  { id: "B32", th: "food", t: "A food forest in a pocket park", after: "Beacon Food Forest", city: "Seattle", yr: 2012, fact: "seven acres of public food forest", url: "https://beaconfoodforest.org/",
    g: ["bird","bee","flyingfox"], roles: ["grower","space"], m: [4,5,6,7], dz: ["drought"], adds: ["food","canopy","diversity"],
    i: "A pocket park feeds people, birds and bats", s: "Plant in layers.", h: "Design one pocket park in four layers" },
  { id: "B33", th: "food", t: "Bag the fruit, share the tree", after: "Harvest Without Harm", city: "Victoria", yr: 2021, fact: "bags and sleeves on chosen branches; any net 5 mm or finer since 1 September 2021", url: "https://www.wildlife.vic.gov.au/__data/assets/pdf_file/0030/538176/HarvestWithoutHarm_trifold_Final.pdf",
    g: ["flyingfox","bird","parrot","possum","snake","lizard"], roles: ["label","repair","studio","market"], m: [9,10,11,0,1,2], dz: ["heat"], adds: ["food"],
    i: "Every fruit tree keeps a branch to share", s: "Bag your share. Leave theirs.", h: "{biz} sews fruit bags from offcuts" },
  { id: "B34", th: "food", t: "Start where the rubbish was", after: "CERES", city: "Brunswick East", yr: 1982, fact: "a former tip turned community park", url: "https://beat.com.au/brunswicks-rubbish-tip-turned-green-oasis-ceres-is-battling-to-avoid-closure/",
    g: ["bee","bird","frog","plant"], roles: ["grower","market","coop","space"], m: [2,3,4,8,9], dz: ["drought"], adds: ["food","diversity"],
    i: "Every vacant lot grows something by spring", s: "Start where the rubbish was.", h: "One vacant lot becomes a shade garden" },
  { id: "B35", th: "food", t: "Compost the street", after: "ShareWaste", city: "Australia", yr: 2015, fact: "neighbours sharing compost", url: "https://acehub.org.au/knowledge-hub/case-studies/sharewaste",
    g: ["segmented","beetle","plant","fungi","snail"], roles: ["owner","grower","coop"], m: [9,10,11,0,1,2,3,4,5,6,7,8], dz: ["drought"], adds: ["food"],
    i: "No food scrap on the block goes to landfill", s: "Feed the ground.", h: "Lidded scrap bins at {biz}; mulch trees" },
  { id: "B36", th: "water", t: "Filter the wash", after: "Parry Sound filter pilot", city: "Ontario", yr: 2021, fact: "41% fewer fibres in the town’s wastewater from 97 homes", url: "https://www.greatlakesnow.org/2021/12/14/study-washing-machine-microfibers/",
    g: ["aquatic","waterbird","turtle","frog"], roles: ["fibres","label","reuse"], m: [9,10,11,0,1,2,3,4,5,6,7,8], dz: ["litter"], adds: [],
    i: "No wash on the strip sheds fibres to creek", s: "Catch it in the machine.", h: "{biz} fits fibre filters; lends wash bags" },
  { id: "B37", th: "circular", t: "A monthly repair night", after: "Repair Café", city: "Amsterdam", yr: 2009, fact: "now worldwide", url: "https://www.repaircafe.org/en/",
    g: [], roles: ["repair","space","owner"], m: [9,10,11,0,1,2,3,4,5,6,7,8], dz: ["heat"], adds: [],
    i: "Nothing fixable in an hour is thrown out", s: "Mend before you buy.", h: "{biz} hosts a monthly repair night" },
  { id: "B38", th: "circular", t: "A heat kit to borrow", after: "Library of Things", city: "London", yr: 2014, fact: "borrow instead of buy", url: "https://www.libraryofthings.co.uk/",
    g: ["human"], roles: ["reuse","repair","label","space","coop"], m: [9,10,11,0,1,2], dz: ["heat"], adds: [],
    i: "Every fan and shade sail can be borrowed", s: "Heat gear is shared gear.", h: "A heat-kit shelf at {biz} to borrow from" },
  { id: "B39", th: "circular", t: "One swap-cup for the whole strip", after: "RECUP", city: "Germany", yr: 2016, fact: "deposit cups shared across cafés", url: "https://recup.de/en/",
    g: ["turtle","waterbird"], roles: ["litter","owner","coop","studio"], m: [9,10,11,0,1,2], dz: ["litter"], adds: [],
    i: "No takeaway cup from {place} hits the creek", s: "One cup, every café.", h: "Cafés within 500 m of the creek share a cup" },
  { id: "B40", th: "circular", t: "Bags sewn from offcuts", after: "Boomerang Bags", city: "Burleigh Heads", yr: 2013, fact: "community-sewn bags from offcuts", url: "https://boomerangbags.org/",
    g: ["turtle","waterbird"], roles: ["label","repair","space","coop"], m: [9,10,11,0,1,2,3], dz: ["litter"], adds: [],
    i: "Every counter lends a bag sewn from offcuts", s: "Offcuts are a material.", h: "Sew 100 bags from {biz}’s offcuts in a day" },
  { id: "B41", th: "circular", t: "Buy back, mend, resell", after: "Worn Wear", city: "Patagonia", yr: 2013, fact: "repair and resale of worn gear", url: "https://wornwear.patagonia.com/",
    g: [], roles: ["fashion","repair","reuse"], m: [9,10,11,0,1,2], dz: ["heat"], adds: [],
    i: "Every clothes shop buys back and mends", s: "The best garment is already made.", h: "{biz} takes back worn pieces; tailor mends" },
  { id: "B42", th: "circular", t: "Free repairs, for life", after: "Nudie Jeans", city: "Sweden", yr: null, fact: "free denim repairs for life", url: "https://www.nudiejeans.com/repair",
    g: [], roles: ["label","repair","fashion"], m: [9,10,11,0,1,2,3], dz: ["heat"], adds: [],
    i: "Every label here repairs what it sold", s: "Make it to mend.", h: "A free-repair promise on {biz}’s labels" },
  { id: "B43", th: "circular", t: "Ask who made it", after: "Fashion Revolution", city: "UK", yr: 2013, fact: "begun after the Rana Plaza collapse; #WhoMadeMyClothes", url: "https://www.fashionrevolution.org/",
    g: [], roles: ["fashion","label"], m: [3], dz: ["heat"], adds: [],
    i: "Every garment can say who made it", s: "Traceable or not at all.", h: "Ask {biz} who made it; print the answer" },
  { id: "B44", th: "circular", t: "Swap a season’s wardrobe", after: "The Clothing Exchange", city: "Melbourne", yr: null, fact: "swap events across Australia", url: "http://www.events.clothingexchange.com.au/about",
    g: [], roles: ["reuse","fashion","label","space"], m: [9,10,11,0,1,2,3,4,5,6,7,8], dz: ["heat"], adds: [],
    i: "One Saturday a season, the strip swaps", s: "Swap, don’t shop.", h: "A seasonal swap at {biz}; tailor the rest" },
  { id: "B45", th: "diversity", t: "Stop spraying the footpath", after: "Pesticide-Free Towns", city: "UK", yr: 2015, fact: "over 30 councils committed to going pesticide-free by 2021", url: "https://www.pan-uk.org/a-lesson-in-resilience-pesticide-free-towns-campaign-continues-to-bloom/",
    g: ["orb","spider","mantis","bug","grasshopper","wasp","fly","snail","bee","butterfly"], roles: ["poison","grower","owner"], m: [8,9,10,11,0,1,2], dz: ["poison","drought"], adds: ["pollination","diversity"],
    i: "No footpath in {place} is sprayed", s: "A weed in flower is a meal.", h: "Hand-weed the strip at {biz} each month" },
  { id: "B46", th: "circular", t: "A container drop for a cause", after: "Container Deposit Scheme", city: "Victoria", yr: 2023, fact: "3 billion containers returned by April 2026", url: "https://www.visy.com/newsroom/2026/3-billion-containers-returned-through-victorias-container-deposit-scheme",
    g: ["turtle","waterbird"], roles: ["litter","owner","space"], m: [9,10,11,0,1,2], dz: ["litter"], adds: [],
    i: "Every can is worth more to us than the creek", s: "Value the throwaway.", h: "A 10c container drop at {biz} for a cause" },
  { id: "B47", th: "cats", t: "Cat runs before the curfew", after: "Merri-bek cat curfew", city: "Merri-bek", yr: 2027, fact: "cats in from 7 pm from April 2027", url: "https://conversations.merri-bek.vic.gov.au/domestic-animal-management-plan-2025-2029/about-cat-curfew",
    g: ["bird","lizard","possum","mammal","cat"], roles: ["vet","pets","studio","repair"], m: [9,10,11,0,1,2], dz: ["cats"], adds: ["diversity"],
    i: "Every cat is safe inside by night", s: "Curious cats, safe birds.", h: "Build a cat run from offcuts with {biz}" },
  { id: "B48", th: "cats", t: "Desex before four months", after: "Early-age desexing", city: "Agriculture Victoria", yr: null, fact: "a kitten can be pregnant at four months", url: "https://agriculture.vic.gov.au/livestock-and-animals/animal-welfare-victoria/cats/health/early-age-desexing",
    g: ["cat","bird"], roles: ["vet","pets"], m: [8,9,10,11,0], dz: ["cats"], adds: [],
    i: "No kitten is born in a laneway this summer", s: "If you feed it, desex it.", h: "{biz} runs a desexing day by four months" },
  { id: "B49", th: "heat", t: "Green the laneway, wall to wall", after: "Greening Laneways", city: "City of Melbourne", yr: 2017, fact: "laneways greened with their neighbours", url: "https://www.melbourne.vic.gov.au/greening-laneways",
    g: ["bird","bee","human"], roles: ["owner","studio","space"], m: [2,3,4,5], dz: ["heat"], adds: ["canopy","pollination"],
    i: "The lane behind {biz} is green wall to wall", s: "Walls are ground too.", h: "Climbers on wires for the sunniest wall" },
  { id: "B50", th: "heat", t: "A shade pavilion of Country", after: "The Living Pavilion", city: "University of Melbourne", yr: 2019, fact: "Indigenous-led, planted with indigenous species", url: "https://nespurban.edu.au/platforms/living-pavilion/",
    g: ["plant","bee","human"], roles: ["space","studio","grower"], m: [2,3,4,8,9], dz: ["heat","flower"], adds: ["pollination","diversity"],
    i: "Indigenous plants shade the strip in summer", s: "Learn from Country first.", h: "Co-design it, led by Wurundjeri knowledge" },
];
