/* Direct Action · twenty example W.I.S.H. stories, marked EX wherever they appear, always on the map as receipts.
   Each is a praxis poem at a different scale and in a different mode, tied to real places around its life.
   W draws on an essay (Aeon), I on what research shows about people (worry, hope, habits), S on a design principle
   (circular, biophilic, design justice, tactical urbanism), H on a case that worked (a brief, an award). src: those sources.
   nodes: what each string was tied to, at a bearing (degrees) and a distance (metres) from the life. */
window.DA_EXAMPLES = [
  {
    code: 'DA-0RNG', at: '2026-10-06T10:00:00+11:00', brief: 'B43',
    pin: { lat: -37.7841, lng: 144.9515, n: 'Pongo abelii', cn: 'Sumatran Orangutan', ic: 'Mammalia', g: 'ape', place: 'PARKVILLE' },
    threat: 'El Niño fires burn Sumatra’s forests', when: 'DROUGHT · JAN–MAR', deg: 3,
    lines: { w: 'Fires burned ~900,000 ha of Indonesia by Aug', i: 'Zoo orangutans nest in cloth from Sumatra', s: 'Plastic out. Forest fibre in.', h: 'Brunswick studio + Sumatran weavers: nest kit' },
    nodes: [
      { k: 'a', t: 'biz', n: 'A Brunswick studio', role: 'studio', b: 20, d: 420 },
      { k: 'b', t: 'biz', n: 'A local label', role: 'label', b: 70, d: 380 },
      { k: 'c', t: 'group', n: 'Friends of Royal Park', b: 160, d: 300 },
    ],
    edges: [['pin', 'a'], ['a', 'b'], ['pin', 'c']],
  },
  {
    code: 'DA-B0GN', at: '2026-10-04T21:30:00+11:00', brief: 'B26',
    pin: { lat: -37.7680, lng: 144.9612, n: 'Agrotis infusa', cn: 'Bogong Moth', ic: 'Insecta', g: 'moth', place: 'BRUNSWICK' },
    threat: 'Hot nights, few flowers, lights pull them in', when: 'DRY FLOWERING · NOV–JAN', deg: 3,
    lines: { w: 'Bogong moths fell 99.5% from 2018 to 2021', i: 'Sydney Rd dark enough for moths to fly home', s: 'Dark is a habitat.', h: 'Shopfronts off at close, now until December' },
    nodes: [
      { k: 'a', t: 'biz', n: 'Sydney Rd shopfronts', role: 'light', b: 0, d: 120 },
      { k: 'b', t: 'biz', n: 'A sign printer', role: 'studio', b: 120, d: 260 },
    ],
    edges: [['pin', 'a'], ['a', 'b']],
  },
  {
    code: 'DA-GHFF', at: '2026-10-02T17:10:00+11:00', brief: 'B06',
    pin: { lat: -37.7808, lng: 144.9608, n: 'Pteropus poliocephalus', cn: 'Grey-headed Flying-fox', ic: 'Mammalia', g: 'flyingfox', place: 'PRINCES HILL' },
    threat: 'Dry heat over 38°C can kill a camp in hours', when: 'EARLY HEAT · OCT–NOV', deg: 4,
    lines: { w: '~1,000 flying-fox pups died of heat, Jan 2026', i: 'Every fallen bat found in minutes, not hours', s: 'Help with a pin, not a hand.', h: '20 heat spotters: never touch, call 136 186' },
    nodes: [
      { k: 'a', t: 'group', n: 'Friends of Royal Park', b: 250, d: 480 },
      { k: 'b', t: 'biz', n: 'A print shop', role: 'studio', b: 80, d: 300 },
    ],
    edges: [['pin', 'a'], ['pin', 'b']],
  },
  {code: "DA-RPR4", at: "2026-10-08T18:40:00+11:00", brief: "B37", mode: "SKILL SHARING", scale: "A STRIP", pin: {lat: -37.7646, lng: 144.9606, n: "Homo sapiens", cn: "People", ic: "Mammalia", g: "human", place: "BRUNSWICK"}, threat: "Heatwaves: the deadliest hazard here", when: "HOT NIGHTS · DEC–FEB", deg: 3, lines: {w: "Repair is bold and original, not just thrift", i: "Worry turned into a skill you can lend", s: "Keep every fan in use, at its highest value", h: "Kines: fix-a-fan night before the first 35°C"}, nodes: [{k: "a", t: "biz", n: "Kines", role: "third", b: 40, d: 58},{k: "b", t: "biz", n: "Maker Community", role: "studio", b: 177, d: 596},{k: "c", t: "biz", n: "Circular Campus to Community", role: "repair", b: 200, d: 814},{k: "d", t: "biz", n: "Brunswick Library", role: "third", b: 180, d: 796}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/its-time-to-rediscover-the-art-and-beauty-of-repair","https://doi.org/10.1016/S2542-5196(21)00278-3","https://www.ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview"]},
  {code: "DA-TNY7", at: "2026-10-07T10:15:00+11:00", brief: "B07", mode: "PLANTING", scale: "A BLOCK", pin: {lat: -37.7693, lng: 144.975, n: "Eucalyptus camaldulensis", cn: "River Red Gum", ic: "Plantae", g: "plant", place: "BRUNSWICK EAST"}, threat: "Drought kills slowly; shade goes with it", when: "DROUGHT · JAN–MAR", deg: 3, lines: {w: "Trees are kin, owed a share of justice", i: "Two hours a week in green for every child", s: "Nature in the space, not on a poster", h: "A tiny forest at Fleming Park, block by block"}, nodes: [{k: "a", t: "biz", n: "Fleming Park Hall", role: "third", b: 42, d: 88},{k: "b", t: "biz", n: "CERES Nursery", role: "grower", b: 60, d: 802},{k: "c", t: "biz", n: "Merri Corner Community Garden", role: "third", b: 26, d: 1177},{k: "d", t: "group", n: "Gardens for Wildlife Merri-bek", kind: "gardens", b: 290, d: 1337}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/should-we-act-morally-towards-trees-empedocles-says-yes","https://doi.org/10.1038/s41598-019-44097-3","https://www.terrapinbrightgreen.com/reports/14-patterns/"]},
  {code: "DA-FRG9", at: "2026-10-06T08:30:00+11:00", brief: "B17", mode: "ACTIVIST", scale: "THE SUBURB", pin: {lat: -37.7649, lng: 144.9879, n: "Litoria raniformis", cn: "Growling Grass Frog", ic: "Amphibia", g: "frog", place: "BRUNSWICK EAST"}, threat: "Ponds and drains dry while frogs breed", when: "DROUGHT · JAN–MAR", deg: 4, lines: {w: "Slow hope: real change comes with setbacks", i: "Most want action, and know the rest do too", s: "Centre the ones most affected: the frogs", h: "Adopt every drain on Lygon St, map it"}, nodes: [{k: "a", t: "group", n: "Friends of Merri Creek", kind: "creek", b: 173, d: 1051},{k: "b", t: "group", n: "CERES", kind: "farm", b: 252, d: 499},{k: "c", t: "biz", n: "3RRR (Triple R)", role: "network", b: 249, d: 750},{k: "d", t: "biz", n: "Merri Corner Community Garden", role: "third", b: 312, d: 847}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/we-need-slow-hope-in-a-world-of-accelerating-ecological-change","https://doi.org/10.1038/s41558-024-01925-3","https://designjustice.org/read-the-principles"]},
  {code: "DA-ANMS", at: "2026-10-05T13:00:00+11:00", brief: "B51", mode: "CONTENT", scale: "THE CITY", pin: {lat: -37.7727, lng: 144.9572, n: "Trichoglossus moluccanus", cn: "Rainbow Lorikeet", ic: "Aves", g: "parrot", place: "BRUNSWICK"}, threat: "Dry flowering: no nectar for lorikeets", when: "DRY FLOWERING · NOV–JAN", deg: 3, lines: {w: "We evolved to be fascinated by animals", i: "Every feed full of animals pays them back", s: "Regenerate nature, not only harm it less", h: "0.5% of each animal-led post to the creek"}, nodes: [{k: "a", t: "biz", n: "Brunswick Design District", role: "network", b: 26, d: 71},{k: "b", t: "biz", n: "Brunswick Music Festival", role: "network", b: 53, d: 497},{k: "c", t: "biz", n: "Sydney Road Brunswick Association", role: "network", b: 36, d: 764},{k: "d", t: "biz", n: "Counihan Gallery", role: "space", b: 79, d: 343}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/why-did-humans-evolve-to-be-so-fascinated-with-other-animals","https://www.undp.org/press-releases/gucci-joins-lions-share-fund-support-wildlife-conservation","https://www.ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview"]},
  {code: "DA-DRK5", at: "2026-10-04T21:10:00+11:00", brief: "B27", mode: "SENSORY", scale: "A CREEK PATH", pin: {lat: -37.7604, lng: 144.9852, n: "Chalinolobus gouldii", cn: "Gould's Wattled Bat", ic: "Mammalia", g: "bat", place: "BRUNSWICK EAST"}, threat: "Roosts in roofs and hollows overheat", when: "HOT NIGHTS · DEC–FEB", deg: 3, lines: {w: "We can't thrive in a world without darkness", i: "Night walks that feel safe in the dark", s: "Prospect and refuge: light low, dark above", h: "Amber, low and timed along the Merri path"}, nodes: [{k: "a", t: "group", n: "CERES", kind: "farm", b: 200, d: 695},{k: "b", t: "biz", n: "The Bike Shed at CERES", role: "repair", b: 184, d: 674},{k: "c", t: "biz", n: "Merri Corner Community Garden", role: "third", b: 280, d: 394},{k: "d", t: "biz", n: "Fleming Park Hall", role: "third", b: 222, d: 1247}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/we-can-t-thrive-in-a-world-without-darkness","https://www.terrapinbrightgreen.com/reports/14-patterns/"]},
  {code: "DA-JYW1", at: "2026-10-03T16:45:00+10:00", brief: "B19", mode: "JOY", scale: "AN AFTERNOON", pin: {lat: -37.7703, lng: 144.9612, n: "Heteronympha merope", cn: "Common Brown", ic: "Insecta", g: "butterfly", place: "BRUNSWICK"}, threat: "Heat withers flowers and caterpillar plants", when: "DRY FLOWERING · NOV–JAN", deg: 3, lines: {w: "It doesn't have to be us versus nature", i: "Joy, for a generation that feels powerless", s: "Awe is a design material", h: "Plant a butterfly line; parade it at dusk"}, nodes: [{k: "a", t: "biz", n: "Brunswick Music Festival", role: "network", b: 53, d: 55},{k: "b", t: "biz", n: "Sydney Road Brunswick Association", role: "network", b: 15, d: 365},{k: "c", t: "biz", n: "Counihan Gallery", role: "space", b: 184, d: 203},{k: "d", t: "biz", n: "Balam Balam Place", role: "third", b: 241, d: 89}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/it-doesnt-have-to-be-us-versus-nature","https://doi.org/10.1016/S2542-5196(21)00278-3","https://www.terrapinbrightgreen.com/reports/14-patterns/"]},
  {code: "DA-PSM2", at: "2026-10-02T14:20:00+10:00", brief: "B24", mode: "CARING", scale: "ONE HOUSE", pin: {lat: -37.7666, lng: 144.9736, n: "Pseudocheirus peregrinus", cn: "Common Ringtail Possum", ic: "Mammalia", g: "possum", place: "BRUNSWICK EAST"}, threat: "Over 35°C possums come to ground by day", when: "EARLY HEAT · OCT–NOV", deg: 4, lines: {w: "Close attention is an art and an act of spirit", i: "Most of us would help if we knew how", s: "Everyone is an expert in their own yard", h: "Shallow water, shade, call (03) 8400 7300"}, nodes: [{k: "a", t: "biz", n: "Coffee Bar Elsie", role: "third", b: 319, d: 100},{k: "b", t: "group", n: "Gardens for Wildlife Merri-bek", kind: "gardens", b: 278, d: 1142},{k: "c", t: "biz", n: "Brunswick Tool Library", role: "repair", b: 145, d: 709},{k: "d", t: "biz", n: "3RRR (Triple R)", role: "network", b: 98, d: 564}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/paying-close-attention-is-an-art-and-an-act-of-the-spirit","https://doi.org/10.1038/s41558-024-01925-3","https://designjustice.org/read-the-principles","https://www.wildlifevictoria.org.au/"]},
  {code: "DA-SK73", at: "2026-09-30T11:05:00+10:00", brief: "B02", mode: "LEARNING", scale: "A SCHOOLYARD", pin: {lat: -37.7586, lng: 144.9468, n: "Zosterops lateralis", cn: "Silvereye", ic: "Aves", g: "bird", place: "BRUNSWICK WEST"}, threat: "Water dries up; small birds die of thirst", when: "EARLY HEAT · OCT–NOV", deg: 3, lines: {w: "Small, slow labour remakes whole landscapes", i: "Children who worry, given ground to tend", s: "Short-term action for long-term change", h: "Lift one square of asphalt each school term"}, nodes: [{k: "a", t: "biz", n: "Campbell Turnbull Library", role: "third", b: 351, d: 483},{k: "b", t: "group", n: "West Brunswick Community Garden and Food Forest", kind: "farm", b: 202, d: 388}], edges: [["pin","a"],["pin","b"]], src: ["https://aeon.co/essays/the-insight-of-darwins-work-on-corals-worms-and-co-evolution","https://doi.org/10.1016/S2542-5196(21)00278-3","https://islandpress.org/books/tactical-urbanism"]},
  {code: "DA-BRF6", at: "2026-09-28T09:40:00+10:00", brief: "B20", mode: "PARTNERSHIP", scale: "A STRIP", pin: {lat: -37.7758, lng: 144.9716, n: "Amegilla (Zonamegilla)", cn: "Blue-banded Bee", ic: "Insecta", g: "bee", place: "CARLTON NORTH"}, threat: "Nectar fails; colonies need water to cool", when: "DRY FLOWERING · NOV–JAN", deg: 3, lines: {w: "Keeping bees means thinking in landscapes", i: "Shops proud to feed bees on their roofs", s: "Partner small: one roof, one shop, one street", h: "Pickles + Elsie: a flowering roof each"}, nodes: [{k: "a", t: "biz", n: "Pickles Milk Bar", role: "third", b: 189, d: 716},{k: "b", t: "biz", n: "Coffee Bar Elsie", role: "third", b: 6, d: 1104},{k: "c", t: "biz", n: "Brunswick Tool Library", role: "repair", b: 53, d: 729},{k: "d", t: "biz", n: "Fleming Park Hall", role: "third", b: 24, d: 866}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/why-keeping-bees-means-thinking-about-landscape-as-a-system","https://islandpress.org/books/tactical-urbanism"]},
  {code: "DA-DPV8", at: "2026-09-26T15:30:00+10:00", brief: "B08", mode: "INTERVENTION", scale: "ONE CAR SPACE", pin: {lat: -37.7689, lng: 144.9631, n: "Tiliqua scincoides", cn: "Eastern Blue-tongued Lizard", ic: "Reptilia", g: "lizard", place: "BRUNSWICK"}, threat: "No logs or litter: no cool place to hide", when: "PEAK · DEC–FEB", deg: 3, lines: {w: "Solarpunk: tech that follows nature's lead", i: "Green streets that lower the stress of heat", s: "Cheap, quick, temporary, then permanent", h: "One car space depaved: logs, leaf litter"}, nodes: [{k: "a", t: "biz", n: "Maker Community", role: "studio", b: 239, d: 224},{k: "b", t: "biz", n: "Brunswick Mechanics Institute", role: "space", b: 204, d: 297},{k: "c", t: "biz", n: "Sydney Road Brunswick Association", role: "network", b: 340, d: 210},{k: "d", t: "biz", n: "Don Bosco Op Shop", role: "reuse", b: 247, d: 114}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/in-solarpunk-cities-of-the-future-tech-follows-natures-lead","https://www.terrapinbrightgreen.com/reports/14-patterns/","https://islandpress.org/books/tactical-urbanism"]},
  {code: "DA-MND4", at: "2026-09-24T12:10:00+10:00", brief: "B43", mode: "FASHION", scale: "A LABEL", pin: {lat: -37.7716, lng: 144.9598, n: "Hortophora biapicata", cn: "Garden Orb-weaver", ic: "Arachnida", g: "orb", place: "BRUNSWICK"}, threat: "Drought starves webs of insects", when: "PEAK · DEC–FEB", deg: 2, lines: {w: "Clothes deserve a philosophy of their own", i: "Secondhand as the first choice, not the last", s: "Design out waste before the first stitch", h: "Op shops + labels: a mend wall on Sydney Rd"}, nodes: [{k: "a", t: "biz", n: "Clothing The Gaps", role: "label", b: 19, d: 611},{k: "b", t: "biz", n: "Otto & Spike", role: "label", b: 15, d: 523},{k: "c", t: "biz", n: "Vinnies Brunswick", role: "reuse", b: 169, d: 382},{k: "d", t: "biz", n: "Mutual Muse", role: "reuse", b: 153, d: 218},{k: "e", t: "biz", n: "RMIT School of Fashion and Textiles", role: "studio", b: 260, d: 112}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"],["d","e"]], src: ["https://aeon.co/essays/why-does-philosophy-hold-clothes-in-such-low-regard","https://www.thredup.com/resale","https://www.ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview"]},
  {code: "DA-CNC7", at: "2026-09-22T07:50:00+10:00", brief: "B28", mode: "EVENT", scale: "ONE WEEKEND", pin: {lat: -37.7722, lng: 144.9601, n: "Pardalotus punctatus", cn: "Spotted Pardalote", ic: "Aves", g: "bird", place: "BRUNSWICK"}, threat: "Water dries up; small birds die of thirst", when: "EARLY HEAT · OCT–NOV", deg: 3, lines: {w: "Backyard birds became a wonder of science", i: "Counting together beats worrying alone", s: "Mystery: half-seen things draw us closer", h: "Four days, every yard: City Nature Challenge"}, nodes: [{k: "a", t: "biz", n: "Brunswick Library", role: "third", b: 46, d: 71},{k: "b", t: "biz", n: "Ecological Justice Hub", role: "third", b: 11, d: 91},{k: "c", t: "biz", n: "Balam Balam Place", role: "third", b: 6, d: 169},{k: "d", t: "biz", n: "Blak Dot Gallery", role: "space", b: 12, d: 137}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/how-the-backyard-bird-became-a-wonder-of-science-and-commerce","https://doi.org/10.1016/S2542-5196(21)00278-3","https://www.terrapinbrightgreen.com/reports/14-patterns/"]},
  {code: "DA-CRM2", at: "2026-09-20T17:25:00+10:00", brief: "B01", mode: "SOCIAL", scale: "A BLOCK", pin: {lat: -37.771, lng: 144.9592, n: "Homo sapiens", cn: "People", ic: "Mammalia", g: "human", place: "BRUNSWICK"}, threat: "Heatwaves: the deadliest hazard here", when: "HOT NIGHTS · DEC–FEB", deg: 4, lines: {w: "The commons: cooperation over scarcity", i: "Most would open a door if others did too", s: "Design with the block, not for it", h: "Kines and the library: cool rooms over 35°C"}, nodes: [{k: "a", t: "biz", n: "Kines", role: "third", b: 12, d: 773},{k: "b", t: "biz", n: "Brunswick Library", role: "third", b: 123, d: 155},{k: "c", t: "biz", n: "Brunswick Baths", role: "third", b: 56, d: 51},{k: "d", t: "biz", n: "Balam Balam Place", role: "third", b: 71, d: 103}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/the-challenge-of-reclaiming-the-commons-from-capitalism","https://doi.org/10.1038/s41558-024-01925-3","https://designjustice.org/read-the-principles"]},
  {code: "DA-TR33", at: "2026-09-18T19:35:00+10:00", brief: "B04", mode: "CREATIVE", scale: "ONE TREE", pin: {lat: -37.78, lng: 144.9562, n: "Ninox strenua", cn: "Powerful Owl", ic: "Aves", g: "owl", place: "PARKVILLE"}, threat: "Hot roosts by day; baited rats by night", when: "EARLY HEAT · OCT–NOV", deg: 3, lines: {w: "Restore like a conservator: slow, reversible", i: "People write love letters to trees", s: "Make it reversible, make it beautiful", h: "Give the roost gum an email; print replies"}, nodes: [{k: "a", t: "group", n: "Friends of Royal Park", kind: "park", b: 210, d: 978},{k: "b", t: "biz", n: "Counihan Gallery", role: "space", b: 26, d: 973},{k: "c", t: "biz", n: "Blak Dot Gallery", role: "space", b: 20, d: 1068},{k: "d", t: "biz", n: "Pickles Milk Bar", role: "third", b: 101, d: 1266}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/what-restoration-ecology-could-learn-from-art-conservation","https://aeon.co/essays/what-restoration-ecology-could-learn-from-art-conservation"]},
  {code: "DA-FRT6", at: "2026-09-16T10:30:00+10:00", brief: "B33", mode: "PLANTING", scale: "A LANEWAY", pin: {lat: -37.7614, lng: 144.9452, n: "Platycercus eximius", cn: "Eastern Rosella", ic: "Aves", g: "parrot", place: "BRUNSWICK WEST"}, threat: "Dry flowering: no nectar for lorikeets", when: "DRY FLOWERING · NOV–JAN", deg: 3, lines: {w: "Organisms shape the world that shapes them", i: "Fruit left to rot is a neighbour unmet", s: "Circulate food at its highest value", h: "Bag the branch: nets 5 mm or finer, by law"}, nodes: [{k: "a", t: "group", n: "West Brunswick Community Garden and Food Forest", kind: "farm", b: 187, d: 49},{k: "b", t: "biz", n: "Campbell Turnbull Library", role: "third", b: 5, d: 792}], edges: [["pin","a"],["pin","b"]], src: ["https://aeon.co/essays/organisms-are-not-passive-recipients-of-evolutionary-forces","https://www.ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview"]},
  {code: "DA-MSH1", at: "2026-09-14T20:00:00+10:00", brief: "B53", mode: "MESH", scale: "THE SUBURB", pin: {lat: -37.7681, lng: 144.9621, n: "Homo sapiens", cn: "People", ic: "Mammalia", g: "human", place: "BRUNSWICK"}, threat: "Heatwaves: the deadliest hazard here", when: "HOT NIGHTS · DEC–FEB", deg: 4, lines: {w: "Tech broke our tie to the wild; it can mend", i: "Less powerless when the street can talk", s: "Design to sustain, heal and empower", h: "A mesh node at each partner café, solar"}, nodes: [{k: "a", t: "biz", n: "Kines", role: "third", b: 348, d: 444},{k: "b", t: "biz", n: "Coffee Bar Elsie", role: "third", b: 76, d: 976},{k: "c", t: "biz", n: "Brunswick Music Festival", role: "network", b: 189, d: 214},{k: "d", t: "biz", n: "Ecological Justice Hub", role: "third", b: 203, d: 400},{k: "e", t: "biz", n: "Brunswick Mechanics Institute", role: "space", b: 185, d: 362}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"],["d","e"]], src: ["https://aeon.co/essays/tech-broke-our-relationship-with-wilderness-can-it-mend-it-too","https://doi.org/10.1016/S2542-5196(21)00278-3","https://designjustice.org/read-the-principles","https://meshtastic.org/"]},
  {code: "DA-PDG3", at: "2026-09-12T13:15:00+10:00", brief: "B52", mode: "PLEDGE", scale: "A COUNTER", pin: {lat: -37.7816, lng: 144.9709, n: "Acanthorhynchus tenuirostris", cn: "Eastern Spinebill", ic: "Aves", g: "bird", place: "CARLTON NORTH"}, threat: "Water dries up; small birds die of thirst", when: "DRY FLOWERING · NOV–JAN", deg: 3, lines: {w: "Hopeful pessimism: despair is not the answer", i: "Visitors want to promise, not only consume", s: "A promise in ink outlasts a promise said", h: "Pickles: sign the pledge at the till, printed"}, nodes: [{k: "a", t: "biz", n: "Pickles Milk Bar", role: "third", b: 218, d: 80},{k: "b", t: "biz", n: "Carlton Library", role: "third", b: 176, d: 876},{k: "c", t: "biz", n: "Bargoonga Nganjin, North Fitzroy Library", role: "third", b: 108, d: 1102},{k: "d", t: "biz", n: "Carlton Farmers’ Market", role: "market", b: 168, d: 1084}], edges: [["pin","a"],["pin","b"],["b","c"],["c","d"]], src: ["https://aeon.co/essays/in-these-dark-times-the-virtue-we-need-is-hopeful-pessimism","https://www.dandad.org/insights/awards/palau-pledge-case-study-insights","https://www.dandad.org/insights/awards/palau-pledge-case-study-insights","https://www.dandad.org/insights/awards/palau-pledge-case-study-insights"]}
];
